FROM golang:latest as builder

WORKDIR /go-modules

COPY . ./

# Building using -mod=vendor, which will utilize the vendor directory
RUN CGO_ENABLED=0 GOOS=linux go build -v -mod=vendor -o aggregate ttnmapper-postgres-insert-raw/cmd/aggregate

FROM scratch
WORKDIR /root/

COPY --from=builder /go-modules/aggregate .
COPY conf.json .

CMD ["./aggregate"]